### ISSUE TITLE
Add check and install for needed packages

### ISSUE THREAD

**Issue by gOOvER** [SergiX44/ISPC-PHPCompiler#1]
I use this Script with Ubuntu 16.04.2. Needed packages are not installed before compile, so compile will end in an error. 

Please add needed packages

**Comment by SergiX44** [comment]
Which packages are needed under Ubuntu 16.10 and which  packages included in the rocket manager are correct and what wrong?

**Comment by budgierless** [comment]
**Ubuntu 16.04 needs:**   libfcgi-dev libfcgi0ldbl libjpeg62-dbg libmcrypt-dev libssl-dev libc-client2007e libc-client2007e-dev libxml2-dev libbz2-dev libcurl4-openssl-dev libjpeg-dev libpng12-dev libfreetype6-dev libkrb5-dev libpq-dev libxml2-dev libxslt1-dev build-essential wget nano
